### ISSUE TITLE
problem logging data item

### ISSUE THREAD

**Issue by nawaz2013** [scc-digitalhub/digitalhub-core#131]
24.10.30 08:12:32.001 (I)             processor.job Received event: {'id': '361ecadd-0ef8-473e-bf40-fa388b1c309a', 'key': 'store://project-etl-ci/run/python+run/361ecadd-0ef8-473e-bf40-fa388b1c309a', 'kind': 'python+run', 'metadata': {'name': '361ecadd-0ef8-473e-bf40-fa388b1c309a', 'updated_by': 'khurshid@fbk.eu', 'project': 'project-etl-ci', 'updated': '2024-10-30T08:12:19.245Z', 'created_by': 'khurshid@fbk.eu', 'created': '2024-10-30T08:12:19.235Z'}, 'name': '361ecadd-0ef8-473e-bf40-fa388b1c309a', 'project': 'project-etl-ci', 'spec': {'outputs': {'dataset': 'dataset'}, 'task': 'python+job://project-etl-ci/download-data:cad09f32-6468-480a-b3ef-a30379fecd60', 'inputs': {'url': 'store://project-etl-ci/dataitem/table/url_data_item:24925b00-f80f-4734-877e-847e4d2e5de6'}, 'function': 'python://project-etl-ci/download-data:cad09f32-6468-480a-b3ef-a30379fecd60', 'python_version': 'PYTHON3_10', 'source': {'source': 'src/download-data.py', 'handler': 'downloader', 'base64': 'CmZyb20gZGlnaXRhbGh1Yl9ydW50aW1lX3B5dGhvbiBpbXBvcnQgaGFuZGxlcgoKQGhhbmRsZXIob3V0cHV0cz1bImRhdGFzZXQiXSkKZGVmIGRvd25sb2FkZXIodXJsKToKICAgICMgcmVhZCBhbmQgcmV3cml0ZSB0byBub3JtYWxpemUgYW5kIGV4cG9ydCBhcyBkYXRhCiAgICBkZiA9IHVybC5hc19kZihmaWxlX2Zvcm1hdD0nY3N2JyxzZXA9IjsiKQogICAgcmV0dXJuIGRmCg==', 'lang': 'python'}, 'parameters': {}, 'local_execution': False}, 'status': {'transitions': [{'status': 'BUILT', 'time': '2024-10-30T08:12:19.244850787Z'}], 'state': 'BUILT'}, 'user': 'khurshid@fbk.eu'} {"worker_id": "0"}
24.10.30 08:12:32.001 (I)             processor.job Starting task. {"worker_id": "0"}
24.10.30 08:12:32.001 (I)             processor.job Configuring function inputs. {"worker_id": "0"}
24.10.30 08:12:32.001 (I)             processor.job Executing run. {"worker_id": "0"}
2024-10-30 08:13:56,973 - ERROR - Some error occurred while logging dataitem. Exception: <class 'TypeError'>. Error: ("ClientError.__init__() missing 1 required positional argument: 'operation_name'",)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/digitalhub/stores/s3/store.py", line 478, in _check_access_to_storage
    client.head_bucket(Bucket=bucket)
  File "/opt/conda/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadBucket operation: Forbidden
During handling of the above exception, another exception occurred:
Traceback (most recent call last):

**Comment by nawaz2013** [comment]
There is a need to make a system/infrastructure test check to make sure system is up and running before running tests.
